---
- name: Working with simple dictionaries
  hosts: localhost
  gather_facts: yes 

  vars_files:
          - ~/ans/vars/yummysnacks.yml

  tasks: 
       - name: show off loop control
         debug: 
                    var: item
         loop: 
                     - server1
                     - server2 
                     - server3
         loop_control:
                     pause: 3
                                    
       - name: loop across complex data
         debug: 
                     msg: "{{ item.name }} belongs to the group {{ item.groups }}"

         loop: "{{ snacks }}"
