---
- name: Intro to looping
  hosts: localhost
  gather_facts: yes

  vars:
          ethlist:
                  - eth0
                  - eth1
                  - eth2
                  - eth3
          ethlist2: [eth4, eth5]
  tasks:
          - name: Task-1 demo var loop
            debug: 
                    msg: "The debug allows us to display to the screen: {{ ethlist }}"
          - name: Task-2 display a tiny loop
            debug: 
                    msg: "Looping the values: {{ item }}"
            loop: "{{ ethlist }}"       

          - name: Task-3 cast local vars into loop
            debug: 
                     var: item
            loop:          
                 
                     - 192.168.70.1
                     - 10.10.0.1 
