---
- name: learning to template via jinja
  gather_facts: yes
  hosts: planetexpress

  #vars:
  #       warpmatter: dark matter
  #       spacedollars: 1000000
  #       cargoinv: slurm cola


  tasks:
          - name: Configure fill in ship.cfg.j2 template and push to remoste hosts
            template:
                    src: ~/ans/templates/ship.cfg.j2
                    dest: ~/ship.cfg

          
