---
- name: Copying files from controller to hosts
  hosts: planetexpress
  gather_facts: yes

  tasks:

         - name: Copy file to kevin's favorite futuerama show    
           copy:
             src: /home/student/ans/files/fryresume.txt 
             ##dest: ~/
             dest: "/home/{{ ansible_user }}/"

         - name: download a file to my remote servers
           get_url:
                   url: http://www.clamav.net/downloads/production/clamav-0.99.3.tar.gz
                   dest: ~/clamav-0.99.3.tar.gz    

